### PR TITLE
Test 6.2.0rc1

### PR DESCRIPTION
**Pull request by seisman**

### CODE REVIEW

**Comment by maxrjones** [comment]
This seems like a problem to me:
```
DIR_DCW                        = /Users/meghanj/GMT/data/dcw-gmt-2.0.0
```

**Comment by seisman** [comment]
It's a long-term known issue, but it should work, because GMT tries to find DCW in many places.

**Comment by seisman** [comment]
The macOS bundle fails (https://github.com/GenericMappingTools/gmt-release-testbot/pull/26/checks?check_run_id=2335289363):
```
+ gmt end
Error: rt [ERROR]: System call [gs -q -dNOSAFER -dNOPAUSE -dBATCH -sDEVICE=bbox -DPSL_no_pagefill -dMaxBitmap=2147483647 -dUseFastColor=true '/Users/runner/.gmt/sessions/gmt_session.1148/gmt_0.ps-' 2> '/Users/runner/.gmt/sessions/gmt_session.1148/psconvert_1164c.bb'] returned error 256.
Error: ROR]: Failed to call psconvert
Error: ROR]: gmtinit_process_figures returned error 79
Error: Process completed with exit code 79.
```
It seems something wrong with the bundled gs, but it works for me locally.

**Comment by maxrjones** [comment]
I'm at a loss for what's going on. Could it be worth trying with macOS 11.2?

**Comment by seisman** [comment]
github actions only support 10.15 and 11.0

**Comment by maxrjones** [comment]
The splash startup screen includes this as a necessary step for running scripts:
```export GS_LIB=${GMTHOME}/share/ghostscript/9.53.3/Resource/Init```
I think we should try adding that to `install-gmt-via-bundle.sh`. Do you want me to either create a new PR or push to 6.2.0rc1?

**Comment by seisman** [comment]
> The splash startup screen includes this as a necessary step for running scripts:
> `export GS_LIB=${GMTHOME}/share/ghostscript/9.53.3/Resource/Init`
> I think we should try adding that to `install-gmt-via-bundle.sh`. Do you want me to either create a new PR or push to 6.2.0rc1?

Please push directly to this branch.

**Comment by maxrjones** [comment]
Bundles pass now. I would like to push a commit with `GMT_VERSION: 6.2.0_eefd707_2021.04.06` to check the windows installer. Is that OK with you?

**Comment by seisman** [comment]
Yes to me.

**Pull request closed without merging**
